### PR TITLE
fix obsolete bsc version bug

### PR DESCRIPTION
**Pull request by pwang7**
fix the bug of the obsolete bsc version ifeq statement in Makefile.connectal.build

### CODE REVIEW

**Comment by jameyhicks** [comment]
Which version of Bluespec are you using?

**Comment by pwang7** [comment]
> Which version of Bluespec are you using?

I'm using the latest version:

Bluespec Compiler, version 2022.01 (build 066c7a8)
This is free software; for source code and copying conditions, see
https://github.com/B-Lang-org/bsc

Invoking command line:
bsc -v

**Comment by jameyhicks** [comment]
I'm pretty sure it should be:
`else ifeq ($(shell test $(BSCMAJOR) -le 2019 &>/dev/null && echo obsolete),)
        BSIM_LIBRARY_DIR = $(BLUESPECDIR)/Bluesim/g++4_64
        CXXFLAGS_BSIM += -DBSC_OBSOLETE
else
        BSIM_LIBRARY_DIR = $(BLUESPECDIR)/Bluesim
endif`

**Comment by pwang7** [comment]
> I'm pretty sure it should be:
```Makefile
else ifeq ($(shell test $(BSCMAJOR) -le 2019 &>/dev/null && echo obsolete),) 
    BSIM_LIBRARY_DIR = $(BLUESPECDIR)/Bluesim/g++4_64
    CXXFLAGS_BSIM += -DBSC_OBSOLETE
else
    BSIM_LIBRARY_DIR = $(BLUESPECDIR)/Bluesim endif
```

Yes, your reply is correct, and that's exactly my PR. The original Makefile.connectal.build is wrong:
https://github.com/cambridgehackers/connectal/blob/master/scripts/Makefile.connectal.build#L76-L81

**Comment by pwang7** [comment]
> I'm pretty sure it should be: 
```Makefile
else ifeq ($(shell test $(BSCMAJOR) -le 2019 &>/dev/null && echo obsolete),)
    BSIM_LIBRARY_DIR = $(BLUESPECDIR)/Bluesim/g++4_64
    CXXFLAGS_BSIM += -DBSC_OBSOLETE
else
    BSIM_LIBRARY_DIR = $(BLUESPECDIR)/Bluesim endif
```
Your above reply is correct, my PR is exactly the same as your reply, but the original Makefile.connectal.build is wrong:
https://github.com/cambridgehackers/connectal/blob/master/scripts/Makefile.connectal.build#L76-L81
```Makefile
else ifeq ($(shell test $(BSCMAJOR) -le 2019 &>/dev/null && echo obsolete),)
	BSIM_LIBRARY_DIR = $(BLUESPECDIR)/Bluesim
else
	BSIM_LIBRARY_DIR = $(BLUESPECDIR)/Bluesim/g++4_64
	CXXFLAGS_BSIM += -DBSC_OBSOLETE
```

**Review by jameyhicks — APPROVED** [review]
Thank you for fixing this.

**Comment by pwang7** [comment]
> Thank you for fixing this.

You're welcome! Connectal is very good, I like it~

**Pull request merged**
