### PR TITLE
Added Page12 and Memwrite128 example

### PR DESCRIPTION
**Pull request by hanw**

### CODE REVIEW

**Comment by jameyhicks** [comment]
Looks good to me.

When we merge this, you should send a note to the connect all list because drivers will need to be updated.

**Comment by hanw** [comment]
Yeah, and a couple examples also need to be updated.

**Comment by jameyhicks** [comment]
Updated to use larger pages?

**Comment by hanw** [comment]
I didn't update /lib/cpp/userReference.h and it is used by 
examples/algo1_nandsim/test.cpp:#include "userReference.h"
examples/algo2_nandsim/test.cpp:#include "userReference.h"
examples/nandsim/testnandsim.cpp:#include "userReference.h"
tests/algo1_flashmodel/flashaccess.cpp:#include "userReference.h"
tests/algo1_flashmodel/test.cpp:#include "userReference.h"
tests/algo1_nandsim_manual/algo1.cpp:#include "userReference.h"

**Pull request merged**
