### PR TITLE
Change aws poller time: 10 times speed.

### PR DESCRIPTION
**Pull request by threonorm**

### CODE REVIEW

**Comment by jankcorn** [comment]
I am not sure why you want to reduce the poll timeout interval down to 1ms.
This will cause the 'event indication'/listening thread in the host program to pop back back and forth between user space & kernel when an indication has _not_ been raised.  (If an indication is detected, then the polling will immediately return to the user, without waiting).

I don't object to accepting this change, but am just wondering if the core problem might be dropped PCIe interrupt indications.  If these indications are being dropped on AWS, then the change is perfectly fine (otherwise, interrupt latency is quite long).

Thanks for looking into this!

**Comment by threonorm** [comment]
I believe interrupts are not working on AWS right now. 
That is the reason why we currently need this active waiting.

**Comment by jameyhicks** [comment]
Deleted 1 character, sped up 10x :) Need to fix AWS interrupts

**Comment by jameyhicks** [comment]
Yes, it is a ridiculous timeout and will change it back once interrupts are debugged.

**Pull request merged**
